apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: user-api-spc
  labels:
    app: user-api
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.example.com"
    roleName: "user-api"
    objects: |
      - objectName: "APP_PASSWORD"
        secretPath: "kv/data/user-api"
        secretKey: "APP_PASSWORD"
